#!/bin/bash
# -*- coding: utf-8 -*-
#***********************************************************
#****************SCRIPT D'ADMINISTRATION VERSION 1**********
#***********************************************************
#***********************************************************
#***********CONTRIBUTEUR: SOURIQUAT......*******************
#***********************************************************
#
# NOTES:
#
# Ce script peut être modifié en implémentant de nouvelles fonctions
# L'indentation doit être claire et les commandes commentées
# Le menu principal du script se trouve à la fin
#Ce script doit être lancer en tant que root
#En cas de rajout de fonction penser à rappeler la fonction dans le menu principal ou dans le sous menu auquel elle est implémentée
#En cas de modification, l'interface doit restée au maximum intuitive
#
#Veuillez crée une ficher et tester votre fonction avant de l'implémenté et indiqué si vous avez besoin d'aide
#
# N'OUBLIEZ PAS DE COMMENTER



#**************************************************************
#**************Fonction Gestion des utilisateurs***************
#**************************************************************
function gestion_utilisateur () {
function creation_supp_utilisateur() { #Fonction_pour_création&suppresion_utilisateur
echo -e " \033[31m Supprimer ou créer un utilisateur ? \033[00m"
echo " Taper s pour supprimer / Taper c pour créer :"
read choix
if [ $choix = "c" ] ; 																	
then
   echo "Entrer le login de l'utilisateur souhaité :"
   read user
   adduser -a $user 2>/dev/null		# 2>/dev/null = redirection output vers la poubelle
    if [ $? -eq 0 ]
    then    						# si le résultat est faux
      echo -e "\033[31m L'utilisateur $user à  bien été créé ! \033[00m"
    else
      echo -e "\033[31m Echec, l'utilisateur $user n'a pas été créé, vérifier vos données... \033[00m"
    fi
   echo "Appuyer sur la touche Entrée pour revenir au menu..."
   read touche					# lecture de la touche entrée
   case $touche in

   *)echo -e "\033[37m**** Reprise du script... ****\033[00m";;
   esac
else
 if [ $choix = "s" ] ;
 then
    echo "Donner le nom de l'utilisateur à supprimer :"
    read utildel
    userdel -r $utildel 2>/dev/null		# suppression avec userdel -r
      if [ $? -eq 0 ]				# et vérification
      then     
           echo -e "\033[31m La suppression de l'utilisateur $utildel est confirmée \033[00m"
      else   
           echo -e "\033[31m Echec, de la suppression de l'utilisateur $utildel, vérifier vos données... \033[00m"
      fi
      echo "Appuyer sur la touche Entrée pour revenir au menu..."
      read touche
      case $touche in

      *)echo -e "\033[37m**** Reprise du script... ****\033[00m";;
      esac
 else
      exit 0
 fi
fi
Menu         #Retour au sous menu de la fonction
}

#****************************************************************************
#****************************Fonction Quitter********************************
#****************************************************************************
function quitter () {
exit
}

#****************************************************************************
#**********************************Fonction MENU*****************************
#****************************************************************************
function Menu () {				# conception du menu Principal
echo ""						# les sous fonctions
echo -e "\033[36m Projet Souriquat\033[00m"
echo -e " 							   \033[36 Contributeur: \033[00m "
echo -e "                         \033[37m _______________________________ \033[00m  "
echo -e "                         \033[37m|    Script d'administration    |\033[00m  "
echo -e "                         \033[37m _______________________________ \033[00m  "
echo""
echo -e "\033[33m*** Menu Principal *** :\033[00m"
echo""
echo "1 - Gestion des utilisateurs"
echo "2 - Quitter"
echo ""
echo "Entrez votre choix :"
read CHOIX					# lecture du choix et appel des fonctions
case $CHOIX in
  1)gestion_utilisateur;;
  2)quitter;;

  *)exit 0;;
esac
}							# FIN de la fonction du menu Principal
if [ ! `id -u` = 0 ]; 				# Vérification de l'identifiant du user
then							# si l'identifiant n'est pas celui de root
   echo -e "\033[31m Ce script doit être exécuté en root \033[00m"		# le script n'est pas exécute,
     echo""												# Sinon accès au menu Principal
     echo "**********************************************"
     echo "Appuyer sur la touche <Entrée> pour quitter..."
     echo "**********************************************"
     read touche
     case $touche in

	*)echo -e "\033[37m**** Reprise du script... ****\033[00m";;
     esac
   exit 0
else
   Menu
fi
}
